### PR TITLE
issue/hitide-ui-42: made potential fix to image links

### PR DESCRIPTION
**Pull request by jbyrne6**
### Changes

- changed source of where collection thumbnail images come from (cmr vs hardcoded)

### Notes

- I am not able to load the affected collections on my development build so I can't test this fix until it is UAT or I can access the proper collections in my HiTIDE development build.

### CODE REVIEW

**Comment by jbyrne6** [comment]
### Update

- I was able to fix the bug that prevented the collections from showing up in my local development branch. It looks good to go now.

**Comment by jbyrne6** [comment]
This PR is associated with #42

**Comment by jamesfwood** [comment]
@jbyrne6 We don't want to add the .vscode dir to the repo.  That's only for the IDE.  Can you take that out?
Thanks!

**Comment by jamesfwood** [comment]
@jbyrne6  Can you look at maybe trying to grab the URL from CMR instead? That seems to be more reliable way, and that url you put in there seems like it could change.

In CMR it looks like this:

{
"Description": "Thumbnail",
"URLContentType": "VisualizationURL",
"Type": "GET RELATED VISUALIZATION",
"URL": "https://podaac.jpl.nasa.gov/Podaac/thumbnails/AMSR2-REMSS-L2P-v8.2.jpg"
},

You can grab the RelatedURL with description Thumbnail, and then return the URL.

**Comment by jamesfwood** [comment]
What do you think @sliu008 ?

**Review by jamesfwood — APPROVED** [review]

**Pull request merged**
