### PR TITLE
Fix/metadata dialog fix: initialSearch variable fix

### PR DESCRIPTION
**Pull request by jbyrne6**
### Changes

- the variable initialSearch was not being set when new collections loaded after logging in via EDL. Added in a step to set this variable when logging in in the Search.js file

### CODE REVIEW

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test this in Hitide UAT.  Thanks!

**Comment by jamesfwood** [comment]
@jbyrne6 Please meet with David on how to test this.  Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT): v**4.16.0-RC.5**
HiTIDE Profile - v4.9.8-rc.1
L2SS-Py - v2.6.0rc3

**Test Complete**

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (OPS)  v4.16.0
HiTIDE Profile - v4.9.8
L2SS-Py - v2.5.0

Test Complete

**Pull request merged**
