### PR TITLE
hitide-ui-23: added resolutions to cloud dataset metadata

### PR DESCRIPTION
**Pull request by jbyrne6**
### Description
Added cmr queries to get Resolution Data for cloud collections

### Testing
-  load up hitide
- click on the "i" icon for a cloud dataset
- check to see if there is a resolution available or if it says "not available". It should not show "NaN x NaN"

### CODE REVIEW

**Review by jamesfwood — APPROVED** [review]

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test hitide UAT for this new spatial resolution fix.

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT): v4.16.0-RC.5
HiTIDE Profile - v4.9.8-rc.1
L2SS-Py - v2.6.0rc3


The Following collections still show 'Spatial Resolution' as 'Not Available' in HiTIDE UAT:

AQUARIUS_L2_SSS_CAP_V5 

AQUARIUS_L2_SSS_V5 

JASON-1_L2_OST_GPN_E 

JASON-1_L2_OST_GPR_E 

JASON-1_L2_OST_GPS_E 

JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F 

JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F

JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F

JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F

JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F 

JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F

JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F

JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F

JASON_CS_S6A_L2_AMR_RAD_NRT

JASON_CS_S6A_L2_AMR_RAD_STC

MERGED_TP_J1_OSTM_OST_CYCLES_V42

SWOT_L2_NALT_IGDR_SSHA_1.0

SWOT_L2_NALT_OGDR_SSHA_1.0

**Comment by jbyrne6** [comment]
- JASON and AQUARIUS: there are no x and y resolution parameters
- SWOT: there are two x and y resolution pairs so need to fix that bug in handling that
- MERGED: I am not sure how to find the resolution of that. I can't find a concept ID to look up in cmr

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test this again in UAT.  We made a new releases:
hitide-ui 4.16.1rc1
hitide-profile 4.10.0-rc.1

**Comment by davidcolemanjpl** [comment]
hitide-ui v4.16.1rc1
hitide-profile v4.10.0-rc.1


User obtained the same results as previous during this testing.

The Following collections show 'Spatial Resolution' as 'Not Available' in HiTIDE-UI (UAT):

**AQUARIUS_L2_SSS_CAP_V5 

AQUARIUS_L2_SSS_V5 

JASON-1_L2_OST_GPN_E 

JASON-1_L2_OST_GPR_E 

JASON-1_L2_OST_GPS_E 

JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F 

JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F

JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F

JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F

JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F 

JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F

JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F

JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F

JASON_CS_S6A_L2_AMR_RAD_NRT

JASON_CS_S6A_L2_AMR_RAD_STC

MERGED_TP_J1_OSTM_OST_CYCLES_V42

SWOT_L2_NALT_GDR_SSHA_1.0

SWOT_L2_NALT_IGDR_SSHA_1.0

SWOT_L2_NALT_OGDR_SSHA_1.0**

**Comment by davidcolemanjpl** [comment]
Related to https://github.com/podaac/hitide-ui/issues/36

**Pull request merged**
